version: "3.8"

services:
  go-api:
    build: .
    container_name: go-api
    expose:
      - "4000"
    restart: unless-stopped

  caddy:
    image: caddy:2.10-alpine
    container_name: caddy
    ports:
      - "4002:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped
    depends_on:
      - go-api
