// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createCourse = `-- name: CreateCourse :exec
INSERT INTO courses (title, pid, subject_code, description, credits, hours_catalog_text, notes, pre_and_corequisites)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCourseParams struct {
	Title              string
	Pid                string
	SubjectCode        string
	Description        string
	Credits            string
	HoursCatalogText   string
	Notes              string
	PreAndCorequisites string
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) error {
	_, err := q.db.ExecContext(ctx, createCourse,
		arg.Title,
		arg.Pid,
		arg.SubjectCode,
		arg.Description,
		arg.Credits,
		arg.HoursCatalogText,
		arg.Notes,
		arg.PreAndCorequisites,
	)
	return err
}

const createSection = `-- name: CreateSection :exec
INSERT INTO sections (term, crn, course_pid, subject, course_number, course_name, section, schedule_type, instructional_method, frequency, time, days, location, date_range, instructor, units, additional_information, enrollment_actual, enrollment_maximum, enrollment_seats_available, waitlist_capacity, waitlist_actual, waitlist_seats_available)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSectionParams struct {
	Term                     string
	Crn                      string
	CoursePid                sql.NullString
	Subject                  string
	CourseNumber             string
	CourseName               string
	Section                  string
	ScheduleType             string
	InstructionalMethod      string
	Frequency                string
	Time                     string
	Days                     string
	Location                 string
	DateRange                string
	Instructor               string
	Units                    string
	AdditionalInformation    string
	EnrollmentActual         int32
	EnrollmentMaximum        int32
	EnrollmentSeatsAvailable int32
	WaitlistCapacity         int32
	WaitlistActual           int32
	WaitlistSeatsAvailable   int32
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) error {
	_, err := q.db.ExecContext(ctx, createSection,
		arg.Term,
		arg.Crn,
		arg.CoursePid,
		arg.Subject,
		arg.CourseNumber,
		arg.CourseName,
		arg.Section,
		arg.ScheduleType,
		arg.InstructionalMethod,
		arg.Frequency,
		arg.Time,
		arg.Days,
		arg.Location,
		arg.DateRange,
		arg.Instructor,
		arg.Units,
		arg.AdditionalInformation,
		arg.EnrollmentActual,
		arg.EnrollmentMaximum,
		arg.EnrollmentSeatsAvailable,
		arg.WaitlistCapacity,
		arg.WaitlistActual,
		arg.WaitlistSeatsAvailable,
	)
	return err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses
WHERE id = ?
`

func (q *Queries) DeleteCourse(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCourse, id)
	return err
}

const deleteSection = `-- name: DeleteSection :exec
DELETE FROM sections
WHERE id = ?
`

func (q *Queries) DeleteSection(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteSection, id)
	return err
}

const getCourse = `-- name: GetCourse :one

SELECT id, created_at, updated_at, title, pid, subject_code, description, credits, hours_catalog_text, notes, pre_and_corequisites
FROM courses
WHERE id = ? LIMIT 1
`

// Courses queries
func (q *Queries) GetCourse(ctx context.Context, id int32) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Pid,
		&i.SubjectCode,
		&i.Description,
		&i.Credits,
		&i.HoursCatalogText,
		&i.Notes,
		&i.PreAndCorequisites,
	)
	return i, err
}

const getCourseByPID = `-- name: GetCourseByPID :one
SELECT id, created_at, updated_at, title, pid, subject_code, description, credits, hours_catalog_text, notes, pre_and_corequisites
FROM courses
WHERE pid = ? LIMIT 1
`

func (q *Queries) GetCourseByPID(ctx context.Context, pid string) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourseByPID, pid)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Pid,
		&i.SubjectCode,
		&i.Description,
		&i.Credits,
		&i.HoursCatalogText,
		&i.Notes,
		&i.PreAndCorequisites,
	)
	return i, err
}

const getSection = `-- name: GetSection :one

SELECT id, created_at, updated_at, term, crn, course_pid, subject, course_number, course_name, section, schedule_type, instructional_method, frequency, time, days, location, date_range, instructor, units, additional_information, enrollment_actual, enrollment_maximum, enrollment_seats_available, waitlist_capacity, waitlist_actual, waitlist_seats_available
FROM sections
WHERE id = ? LIMIT 1
`

// Sections queries
func (q *Queries) GetSection(ctx context.Context, id int32) (Section, error) {
	row := q.db.QueryRowContext(ctx, getSection, id)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Term,
		&i.Crn,
		&i.CoursePid,
		&i.Subject,
		&i.CourseNumber,
		&i.CourseName,
		&i.Section,
		&i.ScheduleType,
		&i.InstructionalMethod,
		&i.Frequency,
		&i.Time,
		&i.Days,
		&i.Location,
		&i.DateRange,
		&i.Instructor,
		&i.Units,
		&i.AdditionalInformation,
		&i.EnrollmentActual,
		&i.EnrollmentMaximum,
		&i.EnrollmentSeatsAvailable,
		&i.WaitlistCapacity,
		&i.WaitlistActual,
		&i.WaitlistSeatsAvailable,
	)
	return i, err
}

const getSectionByTermCRN = `-- name: GetSectionByTermCRN :one
SELECT id, created_at, updated_at, term, crn, course_pid, subject, course_number, course_name, section, schedule_type, instructional_method, frequency, time, days, location, date_range, instructor, units, additional_information, enrollment_actual, enrollment_maximum, enrollment_seats_available, waitlist_capacity, waitlist_actual, waitlist_seats_available
FROM sections
WHERE term = ? AND crn = ? LIMIT 1
`

type GetSectionByTermCRNParams struct {
	Term string
	Crn  string
}

func (q *Queries) GetSectionByTermCRN(ctx context.Context, arg GetSectionByTermCRNParams) (Section, error) {
	row := q.db.QueryRowContext(ctx, getSectionByTermCRN, arg.Term, arg.Crn)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Term,
		&i.Crn,
		&i.CoursePid,
		&i.Subject,
		&i.CourseNumber,
		&i.CourseName,
		&i.Section,
		&i.ScheduleType,
		&i.InstructionalMethod,
		&i.Frequency,
		&i.Time,
		&i.Days,
		&i.Location,
		&i.DateRange,
		&i.Instructor,
		&i.Units,
		&i.AdditionalInformation,
		&i.EnrollmentActual,
		&i.EnrollmentMaximum,
		&i.EnrollmentSeatsAvailable,
		&i.WaitlistCapacity,
		&i.WaitlistActual,
		&i.WaitlistSeatsAvailable,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, created_at, updated_at, title, pid, subject_code, description, credits, hours_catalog_text, notes, pre_and_corequisites
FROM courses
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListCoursesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, listCourses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Pid,
			&i.SubjectCode,
			&i.Description,
			&i.Credits,
			&i.HoursCatalogText,
			&i.Notes,
			&i.PreAndCorequisites,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByCourse = `-- name: ListSectionsByCourse :many
SELECT id, created_at, updated_at, term, crn, course_pid, subject, course_number, course_name, section, schedule_type, instructional_method, frequency, time, days, location, date_range, instructor, units, additional_information, enrollment_actual, enrollment_maximum, enrollment_seats_available, waitlist_capacity, waitlist_actual, waitlist_seats_available
FROM sections
WHERE course_pid = ?
ORDER BY term DESC, crn ASC
`

func (q *Queries) ListSectionsByCourse(ctx context.Context, coursePid sql.NullString) ([]Section, error) {
	rows, err := q.db.QueryContext(ctx, listSectionsByCourse, coursePid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Section
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Term,
			&i.Crn,
			&i.CoursePid,
			&i.Subject,
			&i.CourseNumber,
			&i.CourseName,
			&i.Section,
			&i.ScheduleType,
			&i.InstructionalMethod,
			&i.Frequency,
			&i.Time,
			&i.Days,
			&i.Location,
			&i.DateRange,
			&i.Instructor,
			&i.Units,
			&i.AdditionalInformation,
			&i.EnrollmentActual,
			&i.EnrollmentMaximum,
			&i.EnrollmentSeatsAvailable,
			&i.WaitlistCapacity,
			&i.WaitlistActual,
			&i.WaitlistSeatsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByTerm = `-- name: ListSectionsByTerm :many
SELECT id, created_at, updated_at, term, crn, course_pid, subject, course_number, course_name, section, schedule_type, instructional_method, frequency, time, days, location, date_range, instructor, units, additional_information, enrollment_actual, enrollment_maximum, enrollment_seats_available, waitlist_capacity, waitlist_actual, waitlist_seats_available
FROM sections
WHERE term = ?
ORDER BY crn ASC
`

func (q *Queries) ListSectionsByTerm(ctx context.Context, term string) ([]Section, error) {
	rows, err := q.db.QueryContext(ctx, listSectionsByTerm, term)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Section
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Term,
			&i.Crn,
			&i.CoursePid,
			&i.Subject,
			&i.CourseNumber,
			&i.CourseName,
			&i.Section,
			&i.ScheduleType,
			&i.InstructionalMethod,
			&i.Frequency,
			&i.Time,
			&i.Days,
			&i.Location,
			&i.DateRange,
			&i.Instructor,
			&i.Units,
			&i.AdditionalInformation,
			&i.EnrollmentActual,
			&i.EnrollmentMaximum,
			&i.EnrollmentSeatsAvailable,
			&i.WaitlistCapacity,
			&i.WaitlistActual,
			&i.WaitlistSeatsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourse = `-- name: UpdateCourse :exec
UPDATE courses
SET title = ?, subject_code = ?, description = ?, credits = ?, hours_catalog_text = ?, notes = ?, pre_and_corequisites = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateCourseParams struct {
	Title              string
	SubjectCode        string
	Description        string
	Credits            string
	HoursCatalogText   string
	Notes              string
	PreAndCorequisites string
	ID                 int32
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) error {
	_, err := q.db.ExecContext(ctx, updateCourse,
		arg.Title,
		arg.SubjectCode,
		arg.Description,
		arg.Credits,
		arg.HoursCatalogText,
		arg.Notes,
		arg.PreAndCorequisites,
		arg.ID,
	)
	return err
}

const updateSection = `-- name: UpdateSection :exec
UPDATE sections
SET term = ?, crn = ?, course_pid = ?, subject = ?, course_number = ?, course_name = ?, section = ?, schedule_type = ?, instructional_method = ?, frequency = ?, time = ?, days = ?, location = ?, date_range = ?, instructor = ?, units = ?, additional_information = ?, enrollment_actual = ?, enrollment_maximum = ?, enrollment_seats_available = ?, waitlist_capacity = ?, waitlist_actual = ?, waitlist_seats_available = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateSectionParams struct {
	Term                     string
	Crn                      string
	CoursePid                sql.NullString
	Subject                  string
	CourseNumber             string
	CourseName               string
	Section                  string
	ScheduleType             string
	InstructionalMethod      string
	Frequency                string
	Time                     string
	Days                     string
	Location                 string
	DateRange                string
	Instructor               string
	Units                    string
	AdditionalInformation    string
	EnrollmentActual         int32
	EnrollmentMaximum        int32
	EnrollmentSeatsAvailable int32
	WaitlistCapacity         int32
	WaitlistActual           int32
	WaitlistSeatsAvailable   int32
	ID                       int32
}

func (q *Queries) UpdateSection(ctx context.Context, arg UpdateSectionParams) error {
	_, err := q.db.ExecContext(ctx, updateSection,
		arg.Term,
		arg.Crn,
		arg.CoursePid,
		arg.Subject,
		arg.CourseNumber,
		arg.CourseName,
		arg.Section,
		arg.ScheduleType,
		arg.InstructionalMethod,
		arg.Frequency,
		arg.Time,
		arg.Days,
		arg.Location,
		arg.DateRange,
		arg.Instructor,
		arg.Units,
		arg.AdditionalInformation,
		arg.EnrollmentActual,
		arg.EnrollmentMaximum,
		arg.EnrollmentSeatsAvailable,
		arg.WaitlistCapacity,
		arg.WaitlistActual,
		arg.WaitlistSeatsAvailable,
		arg.ID,
	)
	return err
}
