// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Course struct {
	ID                 int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Title              string
	Pid                string
	SubjectCode        string
	Description        string
	Credits            string
	HoursCatalogText   string
	Notes              string
	PreAndCorequisites string
}

type Section struct {
	ID                       int32
	CreatedAt                time.Time
	UpdatedAt                time.Time
	Term                     string
	Crn                      string
	CoursePid                sql.NullString
	Subject                  string
	CourseNumber             string
	CourseName               string
	Section                  string
	ScheduleType             string
	InstructionalMethod      string
	Frequency                string
	Time                     string
	Days                     string
	Location                 string
	DateRange                string
	Instructor               string
	Units                    string
	AdditionalInformation    string
	EnrollmentActual         int32
	EnrollmentMaximum        int32
	EnrollmentSeatsAvailable int32
	WaitlistCapacity         int32
	WaitlistActual           int32
	WaitlistSeatsAvailable   int32
}
