// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Course struct {
	ID                 int64     `json:"id"`
	CreatedAt          time.Time `json:"createdAt"`
	UpdatedAt          time.Time `json:"updatedAt"`
	Title              string    `json:"title"`
	Pid                string    `json:"pid"`
	SubjectCode        string    `json:"subjectCode"`
	Description        string    `json:"description"`
	Credits            string    `json:"credits"`
	HoursCatalogText   string    `json:"hoursCatalogText"`
	Notes              string    `json:"notes"`
	PreAndCorequisites string    `json:"preAndCorequisites"`
}

type Schedule struct {
	ID                 int64     `json:"id"`
	CreatedAt          time.Time `json:"createdAt"`
	UpdatedAt          time.Time `json:"updatedAt"`
	Token              string    `json:"token"`
	Term               string    `json:"term"`
	SectionCrns        string    `json:"sectionCrns"`
	CollaboratorTokens string    `json:"collaboratorTokens"`
}

type ScheduleCollaborator struct {
	ScheduleID int64     `json:"scheduleId"`
	Token      string    `json:"token"`
	JoinedAt   time.Time `json:"joinedAt"`
}

type Section struct {
	ID                       int64     `json:"id"`
	CreatedAt                time.Time `json:"createdAt"`
	UpdatedAt                time.Time `json:"updatedAt"`
	Term                     string    `json:"term"`
	Crn                      string    `json:"crn"`
	CoursePid                *string   `json:"coursePid"`
	Subject                  string    `json:"subject"`
	CourseNumber             string    `json:"courseNumber"`
	CourseName               string    `json:"courseName"`
	Section                  string    `json:"section"`
	ScheduleType             string    `json:"scheduleType"`
	InstructionalMethod      string    `json:"instructionalMethod"`
	Frequency                string    `json:"frequency"`
	Time                     string    `json:"time"`
	Days                     string    `json:"days"`
	Location                 string    `json:"location"`
	DateRange                string    `json:"dateRange"`
	Instructor               string    `json:"instructor"`
	Units                    string    `json:"units"`
	AdditionalInformation    string    `json:"additionalInformation"`
	EnrollmentActual         int64     `json:"enrollmentActual"`
	EnrollmentMaximum        int64     `json:"enrollmentMaximum"`
	EnrollmentSeatsAvailable int64     `json:"enrollmentSeatsAvailable"`
	WaitlistCapacity         int64     `json:"waitlistCapacity"`
	WaitlistActual           int64     `json:"waitlistActual"`
	WaitlistSeatsAvailable   int64     `json:"waitlistSeatsAvailable"`
}
