// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules
WHERE token = ? AND term = ?
`

type DeleteScheduleParams struct {
	Token string `json:"token"`
	Term  string `json:"term"`
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, arg.Token, arg.Term)
	return err
}

const getCourse = `-- name: GetCourse :one

SELECT id, created_at, updated_at, title, pid, subject_code, description, credits, hours_catalog_text, notes, pre_and_corequisites
FROM courses
WHERE id = ? LIMIT 1
`

// Courses queries
func (q *Queries) GetCourse(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Pid,
		&i.SubjectCode,
		&i.Description,
		&i.Credits,
		&i.HoursCatalogText,
		&i.Notes,
		&i.PreAndCorequisites,
	)
	return i, err
}

const getCourseByPID = `-- name: GetCourseByPID :one
SELECT id, created_at, updated_at, title, pid, subject_code, description, credits, hours_catalog_text, notes, pre_and_corequisites
FROM courses
WHERE pid = ? LIMIT 1
`

func (q *Queries) GetCourseByPID(ctx context.Context, pid string) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourseByPID, pid)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Pid,
		&i.SubjectCode,
		&i.Description,
		&i.Credits,
		&i.HoursCatalogText,
		&i.Notes,
		&i.PreAndCorequisites,
	)
	return i, err
}

const getCourseBySubjectCode = `-- name: GetCourseBySubjectCode :one
SELECT id, created_at, updated_at, title, pid, subject_code, description, credits, hours_catalog_text, notes, pre_and_corequisites
FROM courses
WHERE subject_code = ? OR REPLACE(subject_code, ' ', '') = REPLACE(?, ' ', '')
LIMIT 1
`

type GetCourseBySubjectCodeParams struct {
	SubjectCode string `json:"subjectCode"`
	REPLACE     string `json:"REPLACE"`
}

func (q *Queries) GetCourseBySubjectCode(ctx context.Context, arg GetCourseBySubjectCodeParams) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourseBySubjectCode, arg.SubjectCode, arg.REPLACE)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Pid,
		&i.SubjectCode,
		&i.Description,
		&i.Credits,
		&i.HoursCatalogText,
		&i.Notes,
		&i.PreAndCorequisites,
	)
	return i, err
}

const getSchedule = `-- name: GetSchedule :one

SELECT id, created_at, updated_at, token, term, section_crns
FROM schedules
WHERE token = ? AND term = ?
LIMIT 1
`

type GetScheduleParams struct {
	Token string `json:"token"`
	Term  string `json:"term"`
}

// Schedule queries
func (q *Queries) GetSchedule(ctx context.Context, arg GetScheduleParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getSchedule, arg.Token, arg.Term)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
		&i.Term,
		&i.SectionCrns,
	)
	return i, err
}

const getSectionByCRN = `-- name: GetSectionByCRN :one
SELECT id, created_at, updated_at, term, crn, course_pid, subject, course_number, course_name, section, schedule_type, instructional_method, frequency, time, days, location, date_range, instructor, units, additional_information, enrollment_actual, enrollment_maximum, enrollment_seats_available, waitlist_capacity, waitlist_actual, waitlist_seats_available
FROM sections
WHERE term = ? AND crn = ?
LIMIT 1
`

type GetSectionByCRNParams struct {
	Term string `json:"term"`
	Crn  string `json:"crn"`
}

func (q *Queries) GetSectionByCRN(ctx context.Context, arg GetSectionByCRNParams) (Section, error) {
	row := q.db.QueryRowContext(ctx, getSectionByCRN, arg.Term, arg.Crn)
	var i Section
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Term,
		&i.Crn,
		&i.CoursePid,
		&i.Subject,
		&i.CourseNumber,
		&i.CourseName,
		&i.Section,
		&i.ScheduleType,
		&i.InstructionalMethod,
		&i.Frequency,
		&i.Time,
		&i.Days,
		&i.Location,
		&i.DateRange,
		&i.Instructor,
		&i.Units,
		&i.AdditionalInformation,
		&i.EnrollmentActual,
		&i.EnrollmentMaximum,
		&i.EnrollmentSeatsAvailable,
		&i.WaitlistCapacity,
		&i.WaitlistActual,
		&i.WaitlistSeatsAvailable,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, created_at, updated_at, title, pid, subject_code, description, credits, hours_catalog_text, notes, pre_and_corequisites
FROM courses
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListCoursesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, listCourses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Pid,
			&i.SubjectCode,
			&i.Description,
			&i.Credits,
			&i.HoursCatalogText,
			&i.Notes,
			&i.PreAndCorequisites,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByToken = `-- name: ListSchedulesByToken :many
SELECT id, created_at, updated_at, token, term, section_crns
FROM schedules
WHERE token = ?
ORDER BY term DESC
`

func (q *Queries) ListSchedulesByToken(ctx context.Context, token string) ([]Schedule, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulesByToken, token)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Token,
			&i.Term,
			&i.SectionCrns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByCourse = `-- name: ListSectionsByCourse :many
SELECT id, created_at, updated_at, term, crn, course_pid, subject, course_number, course_name, section, schedule_type, instructional_method, frequency, time, days, location, date_range, instructor, units, additional_information, enrollment_actual, enrollment_maximum, enrollment_seats_available, waitlist_capacity, waitlist_actual, waitlist_seats_available
FROM sections
WHERE course_pid = ?
ORDER BY term DESC, crn ASC
`

func (q *Queries) ListSectionsByCourse(ctx context.Context, coursePid *string) ([]Section, error) {
	rows, err := q.db.QueryContext(ctx, listSectionsByCourse, coursePid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Section
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Term,
			&i.Crn,
			&i.CoursePid,
			&i.Subject,
			&i.CourseNumber,
			&i.CourseName,
			&i.Section,
			&i.ScheduleType,
			&i.InstructionalMethod,
			&i.Frequency,
			&i.Time,
			&i.Days,
			&i.Location,
			&i.DateRange,
			&i.Instructor,
			&i.Units,
			&i.AdditionalInformation,
			&i.EnrollmentActual,
			&i.EnrollmentMaximum,
			&i.EnrollmentSeatsAvailable,
			&i.WaitlistCapacity,
			&i.WaitlistActual,
			&i.WaitlistSeatsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByCourseAndTerm = `-- name: ListSectionsByCourseAndTerm :many
SELECT id, created_at, updated_at, term, crn, course_pid, subject, course_number, course_name, section, schedule_type, instructional_method, frequency, time, days, location, date_range, instructor, units, additional_information, enrollment_actual, enrollment_maximum, enrollment_seats_available, waitlist_capacity, waitlist_actual, waitlist_seats_available
FROM sections
WHERE course_pid = ? AND term = ?
ORDER BY crn ASC
`

type ListSectionsByCourseAndTermParams struct {
	CoursePid *string `json:"coursePid"`
	Term      string  `json:"term"`
}

func (q *Queries) ListSectionsByCourseAndTerm(ctx context.Context, arg ListSectionsByCourseAndTermParams) ([]Section, error) {
	rows, err := q.db.QueryContext(ctx, listSectionsByCourseAndTerm, arg.CoursePid, arg.Term)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Section
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Term,
			&i.Crn,
			&i.CoursePid,
			&i.Subject,
			&i.CourseNumber,
			&i.CourseName,
			&i.Section,
			&i.ScheduleType,
			&i.InstructionalMethod,
			&i.Frequency,
			&i.Time,
			&i.Days,
			&i.Location,
			&i.DateRange,
			&i.Instructor,
			&i.Units,
			&i.AdditionalInformation,
			&i.EnrollmentActual,
			&i.EnrollmentMaximum,
			&i.EnrollmentSeatsAvailable,
			&i.WaitlistCapacity,
			&i.WaitlistActual,
			&i.WaitlistSeatsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCoursesBySubjectCode = `-- name: SearchCoursesBySubjectCode :many
SELECT id, created_at, updated_at, title, pid, subject_code, description, credits, hours_catalog_text, notes, pre_and_corequisites
FROM courses
WHERE subject_code LIKE ? || '%' OR REPLACE(subject_code, ' ', '') LIKE REPLACE(?, ' ', '') || '%'
ORDER BY subject_code
LIMIT 50
`

type SearchCoursesBySubjectCodeParams struct {
	Column1 *string `json:"column1"`
	REPLACE string  `json:"REPLACE"`
}

func (q *Queries) SearchCoursesBySubjectCode(ctx context.Context, arg SearchCoursesBySubjectCodeParams) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, searchCoursesBySubjectCode, arg.Column1, arg.REPLACE)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Pid,
			&i.SubjectCode,
			&i.Description,
			&i.Credits,
			&i.HoursCatalogText,
			&i.Notes,
			&i.PreAndCorequisites,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCoursesBySubjectCodeAndTerm = `-- name: SearchCoursesBySubjectCodeAndTerm :many
SELECT DISTINCT c.id, c.created_at, c.updated_at, c.title, c.pid, c.subject_code, c.description, c.credits, c.hours_catalog_text, c.notes, c.pre_and_corequisites
FROM courses c
INNER JOIN sections s ON (s.subject || s.course_number) = REPLACE(c.subject_code, ' ', '')
WHERE (c.subject_code LIKE ? || '%' OR REPLACE(c.subject_code, ' ', '') LIKE REPLACE(?, ' ', '') || '%')
  AND s.term = ?
ORDER BY c.subject_code
LIMIT 50
`

type SearchCoursesBySubjectCodeAndTermParams struct {
	Column1 *string `json:"column1"`
	REPLACE string  `json:"REPLACE"`
	Term    string  `json:"term"`
}

func (q *Queries) SearchCoursesBySubjectCodeAndTerm(ctx context.Context, arg SearchCoursesBySubjectCodeAndTermParams) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, searchCoursesBySubjectCodeAndTerm, arg.Column1, arg.REPLACE, arg.Term)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Pid,
			&i.SubjectCode,
			&i.Description,
			&i.Credits,
			&i.HoursCatalogText,
			&i.Notes,
			&i.PreAndCorequisites,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCourse = `-- name: UpsertCourse :exec
INSERT INTO courses (title, pid, subject_code, description, credits, hours_catalog_text, notes, pre_and_corequisites)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(pid) DO UPDATE SET
    title = excluded.title,
    subject_code = excluded.subject_code,
    description = excluded.description,
    credits = excluded.credits,
    hours_catalog_text = excluded.hours_catalog_text,
    notes = excluded.notes,
    pre_and_corequisites = excluded.pre_and_corequisites,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertCourseParams struct {
	Title              string `json:"title"`
	Pid                string `json:"pid"`
	SubjectCode        string `json:"subjectCode"`
	Description        string `json:"description"`
	Credits            string `json:"credits"`
	HoursCatalogText   string `json:"hoursCatalogText"`
	Notes              string `json:"notes"`
	PreAndCorequisites string `json:"preAndCorequisites"`
}

func (q *Queries) UpsertCourse(ctx context.Context, arg UpsertCourseParams) error {
	_, err := q.db.ExecContext(ctx, upsertCourse,
		arg.Title,
		arg.Pid,
		arg.SubjectCode,
		arg.Description,
		arg.Credits,
		arg.HoursCatalogText,
		arg.Notes,
		arg.PreAndCorequisites,
	)
	return err
}

const upsertSchedule = `-- name: UpsertSchedule :exec
INSERT INTO schedules (token, term, section_crns)
VALUES (?, ?, ?)
ON CONFLICT(token, term) DO UPDATE SET
    section_crns = excluded.section_crns,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertScheduleParams struct {
	Token       string `json:"token"`
	Term        string `json:"term"`
	SectionCrns string `json:"sectionCrns"`
}

func (q *Queries) UpsertSchedule(ctx context.Context, arg UpsertScheduleParams) error {
	_, err := q.db.ExecContext(ctx, upsertSchedule, arg.Token, arg.Term, arg.SectionCrns)
	return err
}

const upsertSection = `-- name: UpsertSection :exec
INSERT INTO sections (term, crn, course_pid, subject, course_number, course_name, section, schedule_type, instructional_method, frequency, time, days, location, date_range, instructor, units, additional_information, enrollment_actual, enrollment_maximum, enrollment_seats_available, waitlist_capacity, waitlist_actual, waitlist_seats_available)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(term, crn) DO UPDATE SET
    course_pid = excluded.course_pid,
    subject = excluded.subject,
    course_number = excluded.course_number,
    course_name = excluded.course_name,
    section = excluded.section,
    schedule_type = excluded.schedule_type,
    instructional_method = excluded.instructional_method,
    frequency = excluded.frequency,
    time = excluded.time,
    days = excluded.days,
    location = excluded.location,
    date_range = excluded.date_range,
    instructor = excluded.instructor,
    units = excluded.units,
    additional_information = excluded.additional_information,
    enrollment_actual = excluded.enrollment_actual,
    enrollment_maximum = excluded.enrollment_maximum,
    enrollment_seats_available = excluded.enrollment_seats_available,
    waitlist_capacity = excluded.waitlist_capacity,
    waitlist_actual = excluded.waitlist_actual,
    waitlist_seats_available = excluded.waitlist_seats_available,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertSectionParams struct {
	Term                     string  `json:"term"`
	Crn                      string  `json:"crn"`
	CoursePid                *string `json:"coursePid"`
	Subject                  string  `json:"subject"`
	CourseNumber             string  `json:"courseNumber"`
	CourseName               string  `json:"courseName"`
	Section                  string  `json:"section"`
	ScheduleType             string  `json:"scheduleType"`
	InstructionalMethod      string  `json:"instructionalMethod"`
	Frequency                string  `json:"frequency"`
	Time                     string  `json:"time"`
	Days                     string  `json:"days"`
	Location                 string  `json:"location"`
	DateRange                string  `json:"dateRange"`
	Instructor               string  `json:"instructor"`
	Units                    string  `json:"units"`
	AdditionalInformation    string  `json:"additionalInformation"`
	EnrollmentActual         int64   `json:"enrollmentActual"`
	EnrollmentMaximum        int64   `json:"enrollmentMaximum"`
	EnrollmentSeatsAvailable int64   `json:"enrollmentSeatsAvailable"`
	WaitlistCapacity         int64   `json:"waitlistCapacity"`
	WaitlistActual           int64   `json:"waitlistActual"`
	WaitlistSeatsAvailable   int64   `json:"waitlistSeatsAvailable"`
}

func (q *Queries) UpsertSection(ctx context.Context, arg UpsertSectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSection,
		arg.Term,
		arg.Crn,
		arg.CoursePid,
		arg.Subject,
		arg.CourseNumber,
		arg.CourseName,
		arg.Section,
		arg.ScheduleType,
		arg.InstructionalMethod,
		arg.Frequency,
		arg.Time,
		arg.Days,
		arg.Location,
		arg.DateRange,
		arg.Instructor,
		arg.Units,
		arg.AdditionalInformation,
		arg.EnrollmentActual,
		arg.EnrollmentMaximum,
		arg.EnrollmentSeatsAvailable,
		arg.WaitlistCapacity,
		arg.WaitlistActual,
		arg.WaitlistSeatsAvailable,
	)
	return err
}
