// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const getCourse = `-- name: GetCourse :one

SELECT id, created_at, updated_at, title, pid, subject_code, description, credits, hours_catalog_text, notes, pre_and_corequisites
FROM courses
WHERE id = ? LIMIT 1
`

// Courses queries
func (q *Queries) GetCourse(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Pid,
		&i.SubjectCode,
		&i.Description,
		&i.Credits,
		&i.HoursCatalogText,
		&i.Notes,
		&i.PreAndCorequisites,
	)
	return i, err
}

const getCourseByPID = `-- name: GetCourseByPID :one
SELECT id, created_at, updated_at, title, pid, subject_code, description, credits, hours_catalog_text, notes, pre_and_corequisites
FROM courses
WHERE pid = ? LIMIT 1
`

func (q *Queries) GetCourseByPID(ctx context.Context, pid string) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourseByPID, pid)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Pid,
		&i.SubjectCode,
		&i.Description,
		&i.Credits,
		&i.HoursCatalogText,
		&i.Notes,
		&i.PreAndCorequisites,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, created_at, updated_at, title, pid, subject_code, description, credits, hours_catalog_text, notes, pre_and_corequisites
FROM courses
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListCoursesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, listCourses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Pid,
			&i.SubjectCode,
			&i.Description,
			&i.Credits,
			&i.HoursCatalogText,
			&i.Notes,
			&i.PreAndCorequisites,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByCourse = `-- name: ListSectionsByCourse :many
SELECT id, created_at, updated_at, term, crn, course_pid, subject, course_number, course_name, section, schedule_type, instructional_method, frequency, time, days, location, date_range, instructor, units, additional_information, enrollment_actual, enrollment_maximum, enrollment_seats_available, waitlist_capacity, waitlist_actual, waitlist_seats_available
FROM sections
WHERE course_pid = ?
ORDER BY term DESC, crn ASC
`

func (q *Queries) ListSectionsByCourse(ctx context.Context, coursePid sql.NullString) ([]Section, error) {
	rows, err := q.db.QueryContext(ctx, listSectionsByCourse, coursePid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Section
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Term,
			&i.Crn,
			&i.CoursePid,
			&i.Subject,
			&i.CourseNumber,
			&i.CourseName,
			&i.Section,
			&i.ScheduleType,
			&i.InstructionalMethod,
			&i.Frequency,
			&i.Time,
			&i.Days,
			&i.Location,
			&i.DateRange,
			&i.Instructor,
			&i.Units,
			&i.AdditionalInformation,
			&i.EnrollmentActual,
			&i.EnrollmentMaximum,
			&i.EnrollmentSeatsAvailable,
			&i.WaitlistCapacity,
			&i.WaitlistActual,
			&i.WaitlistSeatsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionsByCourseAndTerm = `-- name: ListSectionsByCourseAndTerm :many
SELECT id, created_at, updated_at, term, crn, course_pid, subject, course_number, course_name, section, schedule_type, instructional_method, frequency, time, days, location, date_range, instructor, units, additional_information, enrollment_actual, enrollment_maximum, enrollment_seats_available, waitlist_capacity, waitlist_actual, waitlist_seats_available
FROM sections
WHERE course_pid = ? AND term = ?
ORDER BY crn ASC
`

type ListSectionsByCourseAndTermParams struct {
	CoursePid sql.NullString `json:"coursePid"`
	Term      string         `json:"term"`
}

func (q *Queries) ListSectionsByCourseAndTerm(ctx context.Context, arg ListSectionsByCourseAndTermParams) ([]Section, error) {
	rows, err := q.db.QueryContext(ctx, listSectionsByCourseAndTerm, arg.CoursePid, arg.Term)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Section
	for rows.Next() {
		var i Section
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Term,
			&i.Crn,
			&i.CoursePid,
			&i.Subject,
			&i.CourseNumber,
			&i.CourseName,
			&i.Section,
			&i.ScheduleType,
			&i.InstructionalMethod,
			&i.Frequency,
			&i.Time,
			&i.Days,
			&i.Location,
			&i.DateRange,
			&i.Instructor,
			&i.Units,
			&i.AdditionalInformation,
			&i.EnrollmentActual,
			&i.EnrollmentMaximum,
			&i.EnrollmentSeatsAvailable,
			&i.WaitlistCapacity,
			&i.WaitlistActual,
			&i.WaitlistSeatsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCourse = `-- name: UpsertCourse :exec
INSERT INTO courses (title, pid, subject_code, description, credits, hours_catalog_text, notes, pre_and_corequisites)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(pid) DO UPDATE SET
    title = excluded.title,
    subject_code = excluded.subject_code,
    description = excluded.description,
    credits = excluded.credits,
    hours_catalog_text = excluded.hours_catalog_text,
    notes = excluded.notes,
    pre_and_corequisites = excluded.pre_and_corequisites,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertCourseParams struct {
	Title              string `json:"title"`
	Pid                string `json:"pid"`
	SubjectCode        string `json:"subjectCode"`
	Description        string `json:"description"`
	Credits            string `json:"credits"`
	HoursCatalogText   string `json:"hoursCatalogText"`
	Notes              string `json:"notes"`
	PreAndCorequisites string `json:"preAndCorequisites"`
}

func (q *Queries) UpsertCourse(ctx context.Context, arg UpsertCourseParams) error {
	_, err := q.db.ExecContext(ctx, upsertCourse,
		arg.Title,
		arg.Pid,
		arg.SubjectCode,
		arg.Description,
		arg.Credits,
		arg.HoursCatalogText,
		arg.Notes,
		arg.PreAndCorequisites,
	)
	return err
}

const upsertSection = `-- name: UpsertSection :exec
INSERT INTO sections (term, crn, course_pid, subject, course_number, course_name, section, schedule_type, instructional_method, frequency, time, days, location, date_range, instructor, units, additional_information, enrollment_actual, enrollment_maximum, enrollment_seats_available, waitlist_capacity, waitlist_actual, waitlist_seats_available)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(term, crn) DO UPDATE SET
    course_pid = excluded.course_pid,
    subject = excluded.subject,
    course_number = excluded.course_number,
    course_name = excluded.course_name,
    section = excluded.section,
    schedule_type = excluded.schedule_type,
    instructional_method = excluded.instructional_method,
    frequency = excluded.frequency,
    time = excluded.time,
    days = excluded.days,
    location = excluded.location,
    date_range = excluded.date_range,
    instructor = excluded.instructor,
    units = excluded.units,
    additional_information = excluded.additional_information,
    enrollment_actual = excluded.enrollment_actual,
    enrollment_maximum = excluded.enrollment_maximum,
    enrollment_seats_available = excluded.enrollment_seats_available,
    waitlist_capacity = excluded.waitlist_capacity,
    waitlist_actual = excluded.waitlist_actual,
    waitlist_seats_available = excluded.waitlist_seats_available,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertSectionParams struct {
	Term                     string         `json:"term"`
	Crn                      string         `json:"crn"`
	CoursePid                sql.NullString `json:"coursePid"`
	Subject                  string         `json:"subject"`
	CourseNumber             string         `json:"courseNumber"`
	CourseName               string         `json:"courseName"`
	Section                  string         `json:"section"`
	ScheduleType             string         `json:"scheduleType"`
	InstructionalMethod      string         `json:"instructionalMethod"`
	Frequency                string         `json:"frequency"`
	Time                     string         `json:"time"`
	Days                     string         `json:"days"`
	Location                 string         `json:"location"`
	DateRange                string         `json:"dateRange"`
	Instructor               string         `json:"instructor"`
	Units                    string         `json:"units"`
	AdditionalInformation    string         `json:"additionalInformation"`
	EnrollmentActual         int64          `json:"enrollmentActual"`
	EnrollmentMaximum        int64          `json:"enrollmentMaximum"`
	EnrollmentSeatsAvailable int64          `json:"enrollmentSeatsAvailable"`
	WaitlistCapacity         int64          `json:"waitlistCapacity"`
	WaitlistActual           int64          `json:"waitlistActual"`
	WaitlistSeatsAvailable   int64          `json:"waitlistSeatsAvailable"`
}

func (q *Queries) UpsertSection(ctx context.Context, arg UpsertSectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSection,
		arg.Term,
		arg.Crn,
		arg.CoursePid,
		arg.Subject,
		arg.CourseNumber,
		arg.CourseName,
		arg.Section,
		arg.ScheduleType,
		arg.InstructionalMethod,
		arg.Frequency,
		arg.Time,
		arg.Days,
		arg.Location,
		arg.DateRange,
		arg.Instructor,
		arg.Units,
		arg.AdditionalInformation,
		arg.EnrollmentActual,
		arg.EnrollmentMaximum,
		arg.EnrollmentSeatsAvailable,
		arg.WaitlistCapacity,
		arg.WaitlistActual,
		arg.WaitlistSeatsAvailable,
	)
	return err
}
